# App Settings:
server:
    port: 8080
 
spring:
    application:
        name: DropboxWebhooksSpringBootExample

# Dropbox Properties
dropbox:
    app:
        key: todo
        secret: todo
        redirectUri: http://localhost:8080/dropbox/finish-auth
        sessionStore:
            key: dropbox-auth-csrf-token